// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrgtzbadppneiutjmotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZ3R6YmFkcHBuZWl1dGptb3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODQ4MjEsImV4cCI6MjA3MDE2MDgyMX0.f7Gg0euauM0J5EUJ5IA7ONDgx3ymmshQF6gjxeKY-Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});